"""Data v3 additions (3-4 Oct 2026, Jabin/Claude dev time). OWNER: Jabin.
Why: on the frozen test run, aggregate confusion counts (no test text read) showed most family errors were real
'other cricket statistic' questions forced into a specific family, and general cricket questions read as stats.
These phrasings were written from general cricket knowledge, never from the test sets (G-011). hi/ta need native review.
"""
OTHER_STAT = {
    "en": ["Who scored the fastest {g}{fa} century?", "Fastest {g}{fa} fifty ever?", "Who has taken the most {g}{fa} catches?",
           "Most {g}{fa} hat-tricks by a bowler?", "Highest {g}{fa} partnership of all time?", "Who has the most {g}{fa} ducks?",
           "Most {g}{fa} stumpings by a wicketkeeper?", "Who has the most player of the match awards in {g}{fa} cricket?",
           "Longest six ever hit in {g}{fa} cricket?", "Most {g}{fa} maiden overs?", "Who bowled the fastest ball in {g}{fa} cricket?",
           "Most runs in a single over in {g}{fa} cricket?", "Most {g}{fa} dismissals by a keeper?", "Who has the most {g}{fa} run outs?",
           "Most expensive over in {g}{fa} cricket?", "Most extras conceded in a {g}{fa} innings?", "Who hit the most fours in {g}{fa} cricket?",
           "Most consecutive {g}{fa} wins by a team?", "Who has captained in the most {g}{fa} matches as wicketkeeper?",
           "Fastest {g}{fa} double hundred?", "Most {g}{fa} five-wicket hauls?", "Highest {g}{fa} score by a number eleven batter?",
           "Most runs in a calendar year in {g}{fa} cricket?", "Who has the best {g}{fa} bowling strike rate?", "Most {g}{fa} golden ducks?",
           "Lowest {g}{fa} score defended?", "Most {g}{fa} centuries in a losing cause?", "Who has played the most {g}{fa} innings without a duck?",
           "Most {g}{fa} wickets in a single match?", "youngest {g}{fa} centurion", "fastest {g}{fa} hundred by balls",
           "most catches {g}{fa} fielder", "biggest {g}{fa} partnership", "who has most {g}{fa} hat tricks",
           "Most {g}{fa} sixes in one innings?", "Which bowler has the most {g}{fa} wides?"],
    "hi": ["{g}{fa}क्रिकेट में सबसे तेज़ शतक किसने बनाया?", "{g}{fa}क्रिकेट में सबसे तेज़ अर्धशतक किसका है?",
           "{g}{fa}क्रिकेट में सबसे ज़्यादा कैच किसने पकड़े?", "{g}{fa}क्रिकेट में सबसे ज़्यादा हैट्रिक किसकी है?",
           "{g}{fa}क्रिकेट में सबसे बड़ी साझेदारी कौन सी है?", "{g}{fa}क्रिकेट में सबसे ज़्यादा बार शून्य पर कौन आउट हुआ?",
           "{g}{fa}क्रिकेट में सबसे ज़्यादा स्टंपिंग किसने की?", "{g}{fa}क्रिकेट में सबसे ज़्यादा प्लेयर ऑफ द मैच किसके हैं?",
           "{g}{fa}क्रिकेट में सबसे लंबा छक्का किसने मारा?", "{g}{fa}क्रिकेट में एक ओवर में सबसे ज़्यादा रन किसने बनाए?",
           "{g}{fa}क्रिकेट में सबसे ज़्यादा चौके किसने लगाए?", "{g}{fa}क्रिकेट में सबसे ज़्यादा मेडन ओवर किसके हैं?",
           "{g}{fa}क्रिकेट में सबसे तेज़ गेंद किसने फेंकी?", "{g}{fa}क्रिकेट में एक मैच में सबसे ज़्यादा विकेट किसने लिए?",
           "{g}{fa}क्रिकेट में सबसे ज़्यादा पांच विकेट हॉल किसके हैं?", "{g}{fa}क्रिकेट में सबसे कम उम्र में शतक किसने बनाया?"],
    "hi_rom": ["{g}{fa}cricket me sabse tez century kisne banayi?", "{g}{fa}cricket me sabse zyada catch kisne pakde?",
               "{g}{fa}cricket me sabse zyada hat-trick kiski hai?", "{g}{fa}cricket me sabse badi partnership kaunsi hai?",
               "{g}{fa}cricket me sabse zyada duck kiske hain?", "{g}{fa}cricket me sabse lamba chhakka kisne mara?",
               "{g}{fa}cricket me ek over me sabse zyada runs kisne banaye?", "{g}{fa}cricket me sabse zyada player of the match kiske hain?",
               "{g}{fa}cricket me sabse tez fifty kiski hai?", "{g}{fa}cricket me sabse zyada stumping kisne ki?"],
    "ta": ["{g}{fa}கிரிக்கெட்டில் அதிவேக சதம் அடித்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிவேக அரைசதம் யாருடையது?",
           "{g}{fa}கிரிக்கெட்டில் அதிக கேட்ச் பிடித்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிக ஹாட்ரிக் எடுத்தவர் யார்?",
           "{g}{fa}கிரிக்கெட்டில் மிகப்பெரிய பார்ட்னர்ஷிப் எது?", "{g}{fa}கிரிக்கெட்டில் அதிக முறை டக் அவுட் ஆனவர் யார்?",
           "{g}{fa}கிரிக்கெட்டில் அதிக ஸ்டம்பிங் செய்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிக ஆட்ட நாயகன் விருது யாருக்கு?",
           "{g}{fa}கிரிக்கெட்டில் மிக நீளமான சிக்ஸர் அடித்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் ஒரு ஓவரில் அதிக ரன் எடுத்தவர் யார்?",
           "{g}{fa}கிரிக்கெட்டில் அதிக பவுண்டரி அடித்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிக மெய்டன் ஓவர் வீசியவர் யார்?",
           "{g}{fa}கிரிக்கெட்டில் ஒரு போட்டியில் அதிக விக்கெட் எடுத்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிக ஐந்து விக்கெட் எடுத்தவர் யார்?",
           "{g}{fa}கிரிக்கெட்டில் மிக இளம் வயதில் சதம் அடித்தவர் யார்?", "{g}{fa}கிரிக்கெட்டில் அதிவேக பந்து வீசியவர் யார்?"],
    "ta_rom": ["{g}{fa}cricket-la fastest century adichavanga yaaru?", "{g}{fa}cricket-la adhiga catch pidichavanga yaaru?",
               "{g}{fa}cricket-la adhiga hat-trick yaarudhu?", "{g}{fa}cricket-la periya partnership edhu?",
               "{g}{fa}cricket-la adhiga duck yaarukku?", "{g}{fa}cricket-la neelamana six adichadhu yaaru?",
               "{g}{fa}cricket-la oru over-la adhiga run yaaru?", "{g}{fa}cricket-la adhiga player of the match yaarukku?",
               "{g}{fa}cricket-la fastest fifty yaarudhu?", "{g}{fa}cricket-la adhiga stumping yaaru?"],
}
GENERAL = {
    "en": ["How many players are in a cricket team?", "What does LBW mean?", "How does DRS work in cricket?", "What is a no-ball?",
           "How long is a cricket pitch?", "What is the powerplay in T20 cricket?", "How is a free hit given?",
           "What is the Duckworth-Lewis method?", "What is a super over?", "How many overs are in an ODI?",
           "What is a follow-on in Test cricket?", "What is the difference between a bouncer and a beamer?",
           "How do you bowl a googly?", "What does a third umpire do?", "Why do players wear white in Test cricket?",
           "what is a maiden over", "how does the follow on rule work", "what is the impact player rule in ipl"],
    "hi": ["क्रिकेट टीम में कितने खिलाड़ी होते हैं?", "एलबीडब्ल्यू का मतलब क्या है?", "डीआरएस कैसे काम करता है?", "नो-बॉल क्या होती है?",
           "टी20 में पावरप्ले क्या होता है?", "सुपर ओवर क्या होता है?", "फॉलो-ऑन क्या होता है?", "डकवर्थ-लुईस नियम क्या है?"],
    "hi_rom": ["cricket team me kitne players hote hain?", "LBW ka matlab kya hai?", "DRS kaise kaam karta hai?", "super over kya hota hai?",
               "powerplay kya hota hai?", "free hit kab milta hai?"],
    "ta": ["கிரிக்கெட் அணியில் எத்தனை வீரர்கள்?", "எல்பிடபிள்யூ என்றால் என்ன?", "டிஆர்எஸ் எப்படி வேலை செய்கிறது?", "நோ பால் என்றால் என்ன?",
           "டி20-யில் பவர்பிளே என்றால் என்ன?", "சூப்பர் ஓவர் என்றால் என்ன?", "ஃபாலோ ஆன் என்றால் என்ன?", "டக்வொர்த் லூயிஸ் முறை என்ன?"],
    "ta_rom": ["cricket team-la evlo players?", "LBW na enna?", "DRS eppadi work aagudhu?", "super over na enna?", "powerplay na enna?",
               "free hit eppo kudupanga?"],
}

# v4 (4 Oct): men's league names (IPL/BBL/PSL) also appear in gender-neutral rows: per ANNOTATION_RUBRIC 'do not infer gender from the popularity of a competition'.
